name: Publish GPR

on:
  release:
    types: [published]

env:
  NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VERSION: ${GITHUB_REF/refs\/tags\//}

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo $VERSION

      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Lint & Build
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: https://npm.pkg.github.com/
          scope: '@oacore/configs'
      - run: |
          npm install
          npm run lint

      - name: Bump version ${{ steps.get_version.outputs.VERSION }}
        run: npm run version ${{ steps.get_version.outputs.VERSION }} -- --git-tag-version=false  --force-publish --yes

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Bump version ${{ steps.get_version.outputs.VERSION }}
          title: Bump version ${{ steps.get_version.outputs.VERSION }}
          body: Bump package.json version
          branch: bump-version-${{ steps.get_version.outputs.VERSION }}

      - name: Publish package
        run: npm run publish -- --registry='https://npm.pkg.github.com' --yes
