name: Pull request check

on: [push]

env:
  NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.0
        with:
          node-version: '22.x'
      - name: npm install & test
        run: |
          npm install
          npm run lint
